### ISSUE TITLE
FYI: Скобочный формат исследован

### ISSUE THREAD

**Issue by EvilBeaver** [akpaevj/OneSTools.Database#2]
Добрый день. Крутейший репозиторий, спасибо за него!

К вашему сведению, скобочный формат конфигурации достаточно давно разобран энтузиастами почти полностью, все метаданные и их поля известно, как хранятся. Планируете ли делать полный разбор метаданных? Если да, лучше сократить время на исследования. Обращайтесь.

**Comment by akpaevj** [comment]
Добрый день. Со скобочным форматом все просто, у меня есть собственная библиотека для парсинга потока таких данных. С чтением структуры метаданных из базы данных (таблицы Config, Params, и т.п.) несколько сложнее, там надо сидеть и реверсить структуру хранения данных полностью, я проделал эту работу только частично, периодически возвращаясь к этой задаче. Вот как раз информации на эту тему в открытом доступе нет практически никакой, к сожалению

**Comment by akpaevj** [comment]
Но, если у вас есть наработки на эту тему и готовы поделиться, то я с радостью приму помощь:)

**Comment by EvilBeaver** [comment]
Они есть не у меня, но я знаю у кого есть. Вопрос в целях. Если делать такую библиотеку планируете, то попробуйте обратиться к @bambr1975

**Comment by akpaevj** [comment]
Планирую, спасибо за направление
